### PR TITLE
Change compile to implementation

### PR DESCRIPTION
**Pull request by AfzalivE**
Any interest in this change?

### CODE REVIEW

**Comment by writtmeyer** [comment]
I just dropped by, because I wanted to recommend implementing exactly this. So I hope for this to be merged soon!

But maybe a command line option ``-l`` and ``--legacy`` for those that which to keep compile and ``-a`` or ``--api`` for those that wish to use ``api`` instead of ``implementation`` would be a nice addition.

**Comment by AfzalivE** [comment]
Since this wasn't merged for so long and I'd been setting up multiple computers in the last month, I published my version to rubygems.

https://github.com/AfzalivE/alfi
https://rubygems.org/gems/alfi2

Supports any custom prefix and single quotes (double quotes by default)

**Comment by AfzalivE** [comment]
Should I create a pull request for the other features @cesarferreira ?

**Comment by cesarferreira** [comment]
Yes please, sorry guys, had the notifications disabled on this repo :)

Released this version as `0.6.0`

**Pull request merged**
